apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: sqldata
  name: sqldata
spec:
  type: LoadBalancer
  ports:
    - name: "5433"
      port: 5433
      targetPort: 1433
  selector:
    io.kompose.service: sqldata
status:
  loadBalancer: {}
